# Generated by Django 5.1.5 on 2025-05-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Engine_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Failure_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_of_controlled_bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_of_driving_axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model_of_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recovery_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=64)),
                ('engine_number', models.CharField(max_length=64)),
                ('transmission_number', models.CharField(max_length=64)),
                ('drive_axle_number', models.CharField(max_length=64)),
                ('controlled_bridge_number', models.CharField(max_length=64)),
                ('supply_contract_number', models.CharField(max_length=64)),
                ('shipment_date', models.DateField()),
                ('consignee', models.CharField(max_length=64)),
                ('delivery_address', models.CharField(max_length=64)),
                ('equipment', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.client')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.engine_model')),
                ('model_of_controlled_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.model_of_controlled_bridge')),
                ('model_of_driving_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.model_of_driving_axle')),
                ('model_of_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.model_of_equipment')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.service_company')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.transmission_model')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField()),
                ('development', models.IntegerField(default=0)),
                ('description_of_failure', models.CharField(max_length=64)),
                ('used_spare_parts', models.CharField(max_length=64)),
                ('date_of_restoration', models.DateField()),
                ('machine_downtime', models.IntegerField(default=0)),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.failure_node')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.recovery_method')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_maintenance', models.DateField()),
                ('development', models.IntegerField(default=0)),
                ('work_order_number', models.CharField(max_length=64)),
                ('work_order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.machine')),
                ('organization_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.organization_maintenance')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.service_company')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysilant.type_of_maintenance')),
            ],
        ),
    ]
